### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xuexb** [wuyanwen/test20141021#1]
如果是平常没事的时候联系可以参考：

* 编写可运行的`html`代码，但要注意引用资源的路径，比如使用360的`cdn`的jquery
* 如果要练nodejs，可编写可直接运行的`js`文件，本地可以直接跑起来，还有推荐看下`npm`包管理
* 给代码添加`markdown`说明文档，这个既可以练习`md`格式的编写能力，还可以联系文档的能力，实在是一举两得

当然只是建议～加油～

**Comment by xuexb** [comment]
还有可以给自己定目标，可使用`github`上的`markdown`的`todo list`，比如：

- [x] jquery的`html(str || fn)`方法研究
- [ ] seajs运行原理研究

希望对你有帮助

**Comment by xuexb** [comment]
然后在使用`github`的途中忽然发现把`git`的一些命令练熟了。。。然后就练习`github`合并pr和发pr。然后就又了解到集成测试。。。然后。。。


以上是我使用`github`以来学习的一些心得。


如果感觉没用可`close`

**Comment by wuyanwen** [comment]
谢谢，主要是网不好，得翻墙看
